### ISSUE TITLE
Rake structure load executing and timing out on v2.0

### ISSUE THREAD

**Issue by tomily1** [circleci/circleci-docs#2449]
I have tried different options and non seems to work, every step is working fine until I get to `bundle exec rake db:structure:load` command. I tried to rebuild ssh and it works fine when I try running through my terminal(ssh).

```
#!/bin/bash --login
export TERM=rxvt
bundle exec rake db:structure:load
 set_config 
------------
 
(1 row)

(END)rake aborted!
Interrupt: 
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:108:in `system'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:108:in `run_cmd'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/postgresql_database_tasks.rb:80:in `structure_load'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:223:in `structure_load'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:236:in `load_schema'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:255:in `block in load_schema_current'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:254:in `load_schema_current'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:290:in `block (3 levels) in <top (required)>'
/home/ubuntu/taprootfoundation/taprootplus/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/circleci/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/opt/circleci/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
/opt/circleci/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => db:structure:load
(See full trace by running task with --trace)
Too long with no output (exceeded 10m0s)
```

**Comment by smart-alek** [comment]
Hey @tomily1! Issues submitted to this repository should be associated with specific documents. If you're having difficulties, please head over to our [Discuss forum](https://discuss.circleci.com/) or the [Support Center](https://support.circleci.com/hc/en-us). Thanks!
