### ISSUE TITLE
Unsupported class version number [53.0] (maximum 52.0, Java 1.8)

### ISSUE THREAD

**Issue by isuPatches** [circleci/circleci-docs#2709]
# Description
Build runs fine locally for me for SDK's 26 and 27 as well as 16.

# Location
Transforming with proguard but just on the `circleci/android:api-27-alpha` and `circleci/android:api-26-alpha` break

# Steps to Reproduce
- Run build

# Stacktrace

```
Caused by: java.io.IOException: Can't read [/home/circleci/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.3.1/67b7edddfac1935e6e6d9b58d7c7df6db59b1d39/junit-platform-commons-1.3.1.jar(;;;;;;**.class)] (Can't process class [META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))
	at proguard.InputReader.readInput(InputReader.java:188)
	at proguard.InputReader.readInput(InputReader.java:158)
	at proguard.InputReader.readInput(InputReader.java:136)
	at proguard.InputReader.execute(InputReader.java:88)
	at proguard.ProGuard.readInput(ProGuard.java:218)
	at proguard.ProGuard.execute(ProGuard.java:82)
	at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:61)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:253)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:63)
	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:173)
	at com.android.builder.tasks.Job.runTask(Job.java:47)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)
Caused by: java.io.IOException: Can't process class [META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8))
	at proguard.io.ClassReader.read(ClassReader.java:112)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	at proguard.io.JarReader.read(JarReader.java:65)
	at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
	at proguard.InputReader.readInput(InputReader.java:184)
	... 12 more
Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [53.0] (maximum 52.0, Java 1.8)
	at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:145)
	at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:89)
	at proguard.classfile.LibraryClass.accept(LibraryClass.java:306)
	at proguard.io.ClassReader.read(ClassReader.java:86)
	... 19 more
```

**Comment by smart-alek** [comment]
Hey @isuPatches, did this problem come from a specific document?

**Comment by felicianotech** [comment]
@isuPatches No worries. You can open an issue for the Android image here: https://github.com/circleci/circleci-images/issues

Copying and pasting this entire issue there should do.

**Comment by felicianotech** [comment]
@smart-alek Why did you assign to me?

**Comment by smart-alek** [comment]
@felicianotech only because you helped answer it 🙃

**Comment by felicianotech** [comment]
Oh, I thought you wanted me to do something here as a task.
