### ISSUE TITLE
Android Kotlin compilation always fails

### ISSUE THREAD

**Issue by niccorder** [circleci/circleci-docs#2945]
# Description
When circle-ci builds the android application it always fails with this error:
```
Compilation with Kotlin compile daemon was not successful
java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is: 
	java.io.EOFException
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:236)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy97.compile(Unknown Source)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.incrementalCompilationWithDaemon(GradleKotlinCompilerRunner.kt:289)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemon(GradleKotlinCompilerRunner.kt:217)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemonOrFallback(GradleKotlinCompilerRunner.kt:166)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemonOrFallback(GradleKotlinCompilerRunner.kt:63)
	at org.jetbrains.kotlin.compilerRunner.KotlinCompilerRunner.runCompiler(KotlinCompilerRunner.kt:133)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runJvmCompiler(GradleKotlinCompilerRunner.kt:119)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:405)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:309)
	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:222)
	... 63 more
```
Current CI configuration:
```
version: 2
jobs:
  build:
    working_directory: ~/babble-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m -Dkotlin.compiler.execution.strategy=“in-process”
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "babble-color/build.gradle" }}-{{ checksum  "babble-shared/build.gradle" }}-{{ checksum  "babble-widget/build.gradle" }}-{{ checksum  "util-clock/build.gradle" }}
      - run:
          name: Running tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Assembling apk's
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_test_results:
          path: app/build/test-results
```

This builds successfully for me locally, but I can not seem to get circle-ci to do the same.
# Location
When running build through Circle CI.

**Comment by teesloane** [comment]
Hi @niccorder, thanks for filing an issue!

It looks like your issue _might_ be similar to one posted on the CircleCI [discuss forum](https://discuss.circleci.com/t/circleci-2-0-android-with-kotlin/17531) - it sounds like you could be running out of memory. Another user posted some success after bumping their version of Kotlin (although, this was in Oct 2017.) 

Let me know if the linked thread helps, and if not we can try and figure something out!

**Comment by gellertbiro** [comment]
I am having the same issue, tried a lot of variation with heap size and disable parallel executions and everything I could think of or found in the net. Any update on this. (I use the latest Kotlin version: 1.3.21)

**Comment by Tweener** [comment]
Same for me, my builds keep on failing no matter which configuration I try. Any news?
It's quite annoying as we can't release any build. We would prefer to avoid that but we might need to drop CircleCI if there is no solution on the way.

**Comment by michelle-luna** [comment]
@drazisil can you help out with this question?

**Comment by drazisil** [comment]
Notes on https://discuss.circleci.com/t/circleci-2-0-android-with-kotlin/17531/7?u=drazisil indicate that updating Kotlin may solve the issue.

We no longer update the `-alpha` images, so perhaps updating to one of the support tags would help https://hub.docker.com/r/circleci/android/

**Comment by Tweener** [comment]
Hey @drazisil,
Thanks for your feedback.

I'm already using the latest Kotlin version (1.3.21) so I guess that's not the origin of the problem.
I just tried using `android-28` (instead of `android-28-alpha`) Docker image and the problem still persists. It keeps on failing every single time, even though I'm using the `--no-daemon` flag.

**Comment by drazisil** [comment]
It's very possibly something outside our control, but can you please open a ticket at support.circleci.com so we can take a look?

**Comment by niccorder** [comment]
Following up - This is what fixed it for me a while back. 

https://discuss.circleci.com/t/circleci-2-0-android-build-in-android-docker-image-fails-both-on-cloud-and-cli/25288

**Comment by fefranca** [comment]
Hi, this has been a tough one to debug, in the end the following line from [a CircleCI android orb](https://circleci.com/orbs/registry/orb/wordpress-mobile/android) fixed it for me:

`GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false`

My **gradle.properties** is pretty default:
```
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
```

Other project dependencies worth mentioning:
* API Level 28 (`circleci/android:api-28`) 
* Gradle `4.10.2`
* Android Gradle plugin `3.3.2`
* Kotlin `1.3.21`

**Comment by Tweener** [comment]
That did it for me. Thanks a lot @fefranca !

**Comment by Khang-NT** [comment]
For anyone, who still facing this issue regardless how much heap size you set.
Here is the root cause: https://github.com/gradle/gradle/issues/6942
Gradle spawn too many worker in Circle CI container, around 30 workers, then cause out of memory problem (circle CI physic machine has 36 processors).
Solution is manually set max worker to gradle command, e.g:
```
./gradlew .... --max-workers=3; # 3 is enough I guess
```
<img width="268" alt="Screen Shot 2019-09-01 at 1 44 52 PM" src="https://user-images.githubusercontent.com/13332950/64072914-12f03f80-ccc1-11e9-9759-8f884d432d3f.png">

**Comment by HeinousGames** [comment]
For a lot of people, it seems adding the GRADLE_OPTS line helped resolve their unmarshaling error. For me, that line actually broke all of my unit tests before getting to the command that causes the unmarshaling error. For our build, our gradle memory was used up after running all of our unit tests. The solution was to clear the gradle cache after all of the unit tests ran, but before building and pushing to the store. We added the command `rm -fr ~/.gradle/daemon/` to our travis file, and that resolved the unmarshaling error for us.

**Comment by ranvirgorai** [comment]
In **android/gradle.properties** file

I have set my memoriy tweaking configuration and it is workin.
 
`org.gradle.jvmargs=-Xmx6g -XX:MaxPermSize=512m -Dkotlin.compiler.execution.strategy=“in-process”`

**Comment by HerreraMD** [comment]
I'm facing the same issue but this time in flutter. I just updated my kotlin version and nothing elese. 
Though, when I tried to run it, it still worked
