### ISSUE TITLE
Browser testing - Selenium example is outdated

### ISSUE THREAD

**Issue by KalleVuorjoki** [circleci/circleci-docs#2947]
# Description
Two issues:
1) Image referenced in document is not available
```
Starting container circleci/node-jessie-browsers
  image cache not found on this host, downloading circleci/node-jessie-browsers

Error response from daemon: repository circleci/node-jessie-browsers not found: does not exist or no pull access
```
2) If using `circleci/php:7.2.9-apache-node-browsers` image task `Start Selenium` fails. Please document which image it works out-of-box.

```
#!/bin/bash -eo pipefail
java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/circleci/drupal/test-reports/selenium.log.lck
	at org.openqa.grid.selenium.GridLauncherV3.configureLogging(GridLauncherV3.java:209)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:92)
Caused by: java.nio.file.NoSuchFileException: /home/circleci/drupal/test-reports/selenium.log.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:478)
	at java.util.logging.FileHandler.<init>(FileHandler.java:344)
	at org.openqa.grid.selenium.GridLauncherV3.configureLogging(GridLauncherV3.java:204)
	... 1 more
Exited with code 1
```

# Location
https://circleci.com/docs/2.0/browser-testing/#selenium

# Steps to Reproduce

Try to build with following config (copied from link):
```
version: 2
jobs:
  build:
    docker:
      #- image: circleci/node-jessie-browsers
      - image: circleci/php:7.2.9-apache-node-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
```

**Comment by teesloane** [comment]
Hi @KalleVuorjoki ! Thanks for filing an issue. I tested both issues you've reported and both are correct:

I'm seeing this when trying to run the selenium command — I suspect you are too? :
![image](https://user-images.githubusercontent.com/12987958/49093557-5a2d3980-f232-11e8-8e33-884e64950b00.png)

In the meantime, I'll work through the doc to update the outdated parts.

**Comment by iynere** [comment]
@KalleVuorjoki #1 is just a typo, it should be `circleci/node:jessie-browsers`—i'll fix that for u
