### ISSUE TITLE
RE: jekyll/_docs/google-auth.md

### ISSUE THREAD

**Issue by mtedone** [circleci/circleci-docs#500]
I need to use Google Application Default Credentials as explained [here](https://developers.google.com/identity/protocols/application-default-credentials). 

To do so, I'd need to run something like `gcloud auth application-default login` or similar. 

The instructions explained [here](https://circleci.com/docs/google-auth/) didn't work for me. 

The logs show the following:

com.google.cloud.datastore.DatastoreException: Unexpected OK error code with HTTP status code of 401. Message: .
        at com.google.cloud.datastore.spi.DefaultDatastoreRpc.translate(DefaultDatastoreRpc.java:110)
        at com.google.cloud.datastore.spi.DefaultDatastoreRpc.commit(DefaultDatastoreRpc.java:137)
        at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:390)
        at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:387)
        at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:179)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:244)
        at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:386)
        at com.google.cloud.datastore.DatastoreImpl.commitMutation(DatastoreImpl.java:380)
        at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:340)
        at com.google.cloud.datastore.DatastoreHelper.put(DatastoreHelper.java:55)
        at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:315)
[...]

**Comment by mtedone** [comment]
Fixed by setting environment variable $GOOGLE_APPLICATION_CREDENTIALS to ${HOME}/gcloud-service-key.json
